### ISSUE TITLE
Bug in Demo and fix for iPad width.

### ISSUE THREAD

**Issue by dmthomas** [enormego/EGOTableViewPullRefresh#13]
In the RootViewController of the demo, in the viewDidLoad: method you create your EGORefreshTableHeaderView view inside the if statement and then outside the scope of the if statement you send it refreshLastUpdatedDate.

I fixed this and got it to compile by defining view outside of the if statement. (EGORefreshTableHeaderView *view = nil;)

When you're creating the EGORefreshTableHeaderView view you set the width to 320 pixels hardcoded I noticed it getting cut off on the iPad so I changed it to self.tableView.bounds.size.width. Works perfectly.

Great stuff otherwise!

**Comment by devindoty** [comment]
Thanks! The RootViewController is really just for demo, hopefully it's not being used in production code. I've gone ahead and fixed those issues.

**Comment by dmthomas** [comment]
Understood. I was just ensuring the demo worked correctly for others. :-)
