### ISSUE TITLE
iOS 5 must be __unsafe_unretained

### ISSUE THREAD

**Issue by stephenlindauer** [enormego/EGOTableViewPullRefresh#34]
I brought the code into my project which is sdk 5. I got rid of the obvious errors complaining about the "release" errors, but the last one I can't figure out. I'm getting "Existing ivar '_delegate' for unsafe_unretained property 'delegate' must be __unsafe_unretained"

I've tried every combination I could think of within the EGORefreshTableHeaderView.h; adding __unsafe_unretained, removing assign, etc... Has someone done this yet? I'm sure it's a fairly easy change, I'm just new to coding for iPhone and can't figure it out.

**Comment by devindoty** [comment]
If you're compiling under ARC, you can remove the delegate var in the interface. Should look like below. 

@interface EGORefreshTableHeaderView : UIView {
    EGOPullRefreshState _state;

```
UILabel *_lastUpdatedLabel;
UILabel *_statusLabel;
CALayer *_arrowImage;
UIActivityIndicatorView *_activityView;
```

}

@property(nonatomic,assign) id <EGORefreshTableHeaderDelegate> delegate;
