### ISSUE TITLE
Class error

### ISSUE THREAD

**Issue by kolyancz** [enormego/EGOTableViewPullRefresh#5]
I'm getting this after adding this code to my project. And CALayer and other Core graphic things isn't purple, but black.
Can you help me?  

"_OBJC_CLASS_$_RefreshTableHeaderView", referenced from:
      objc-class-ref-to-RefreshTableHeaderView in OrdersViewController.o
      ld: symbol(s) not found
      collect2: ld returned 1 exit status

**Comment by dlinsin** [comment]
have you added CoreGraphics.framework to your project?

**Comment by kolyancz** [comment]
My mistake. I'm using RefreshTableHeaderView.m instead SomethingRefreshTableHeaderView.m.
