### ISSUE TITLE
id _delegate; : 'delegate with assign attribute must be __unsafe_unretained'

### ISSUE THREAD

**Issue by brittanyl** [enormego/EGOTableViewPullRefresh#68]
Hi there, 

In EGORefreshTableHeaderView.h, the line "id _delegate;" keeps throwing me the following error:

delegate with assign attribute must be __unsafe_unretained

Does anyone know how I can fix this? I was under the impression that the following property would keep this error from occurring: 

@property (nonatomic,assign) id <EGORefreshTableHeaderDelegate> delegate;

Thanks,
Brittany

**Comment by shnhrrsn** [comment]
It sounds like you're trying to use this without ARC, this project hasn't been maintained in years and is pretty old code which isn't ARC compatible.

Personally, I'd recommend just using UIRefreshControl, but if you need to use EGOTableViewPullRefresh, follow the steps here to turn off ARC for just these classes: http://stackoverflow.com/questions/6646052/how-can-i-disable-arc-for-a-single-file-in-a-project
