### ISSUE TITLE
Section titles stop at the wrong location

### ISSUE THREAD

**Issue by ryanwilliams** [enormego/EGOTableViewPullRefresh#8]
Because 'contentInset' is used to adjust the padding when loading data the section headers are also pushed down by the same amount.

Another symptom of the same issue is when using 'sectionIndexTitlesForTableView' to show an index down the right side, the index gets squashed down by the contentInset amount.

Screenshot below. Notice the "A" section header has stopped because it thinks its reached the top of the scrollview and the sectionIndex has been squashed down too.

http://i.imgur.com/divYk.png

**Comment by YohannsMonnier** [comment]
We have the same problem here, is there a way to correct it ?

**Comment by seboslaw** [comment]
I second (or third) this issue! Has any of you guys found a workaround?

**Comment by ptz0n** [comment]
Same issue here. Let's get this right?

(Gowalla etc. having the same problem too)

**Comment by devindoty** [comment]
This issue has fixed in the latest commit.
